import { User, Service, UserType } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    nome: "Maria Silva",
    tipo: 'freelancer',
    bio: "Designer gráfica especializada em branding e identidade visual. Apaixonada por criar marcas que contam histórias.",
    avatar: "https://picsum.photos/seed/maria/200"
  },
  {
    id: 2,
    nome: "João Mendes",
    tipo: 'client',
    bio: "Empreendedor digital procurando profissionais criativos para alavancar meu novo projeto de e-commerce.",
    avatar: "https://picsum.photos/seed/joao/200"
  },
  {
    id: 3,
    nome: "Ana Pereira",
    tipo: 'freelancer',
    bio: "Desenvolvedora Full-Stack com 5 anos de experiência em React e Node.js. Foco em aplicações web performáticas.",
    avatar: "https://picsum.photos/seed/ana/200"
  }
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 1,
    titulo: "Criação de logo minimalista",
    autorId: 1,
    preço: "R$ 150",
    prazo: "3 dias",
    descricao: "Desenvolvimento de um logotipo moderno e minimalista para sua marca, com entrega de arquivos em alta resolução e manual da marca simplificado.",
    categoria: "Design Gráfico",
    status: 'disponível',
  },
  {
    id: 2,
    titulo: "Desenvolvimento de landing page",
    autorId: 3,
    preço: "R$ 350",
    prazo: "5 dias",
    descricao: "Criação de uma landing page responsiva e otimizada para conversão utilizando React e Tailwind CSS. Ideal para campanhas de marketing e lançamento de produtos.",
    categoria: "Desenvolvimento Web",
    status: 'disponível',
  },
  {
    id: 3,
    titulo: "Ilustração para redes sociais",
    autorId: 1,
    preço: "R$ 80",
    prazo: "2 dias",
    descricao: "Criação de uma ilustração personalizada para posts em redes sociais (Instagram, Facebook). Estilo a combinar com o cliente.",
    categoria: "Ilustração",
    status: 'em andamento',
    clientId: 2,
  },
  {
    id: 4,
    titulo: "Consultoria de SEO para Blog",
    autorId: 3,
    preço: "R$ 200",
    prazo: "1 semana",
    descricao: "Análise completa do seu blog e plano de ação para otimizar o SEO on-page, melhorar o ranqueamento e aumentar o tráfego orgânico.",
    categoria: "Marketing Digital",
    status: 'concluído',
    clientId: 2,
  },
  {
    id: 5,
    titulo: "Edição de Vídeo para YouTube",
    autorId: 1,
    preço: "R$ 250",
    prazo: "4 dias",
    descricao: "Edição de vídeo com cortes, trilha sonora, e legendas para canal do YouTube.",
    categoria: "Edição de Vídeo",
    status: 'entregue',
    clientId: 2,
    delivery: {
      fileName: 'video_final.mp4',
      message: 'Olá João, segue a primeira versão do vídeo para aprovação!'
    }
  }
];

export const translations: Record<string, Record<string, string>> = {
  'pt-BR': {
    'home': 'Home',
    'dashboard': 'Painel',
    'settings': 'Configurações',
    'login': 'Login',
    'register': 'Cadastro',
    'search_placeholder': 'Buscar por serviços...',
    'profile': 'Perfil',
    'logout': 'Sair',
    'hero_title': 'Encontre os melhores freelancers para o seu projeto',
    'hero_subtitle': 'Milhares de profissionais talentosos prontos para ajudar.',
    'service_card_details': 'Ver Detalhes',
    'footer_about': 'Sobre',
    'footer_terms': 'Termos',
    'footer_support': 'Suporte',
    'login_title': 'Acesse sua conta',
    'login_email': 'Email',
    'login_password': 'Senha',
    'login_button': 'Entrar',
    'login_no_account': 'Não tem uma conta?',
    'register_title': 'Crie sua conta',
    'register_name': 'Nome completo',
    'register_user_type': 'Eu sou um',
    'register_freelancer': 'Freelancer',
    'register_client': 'Cliente',
    'register_button': 'Cadastrar',
    'register_have_account': 'Já tem uma conta?',
    'service_details_by': 'Por',
    'service_details_price': 'Preço',
    'service_details_deadline': 'Prazo',
    'service_details_description': 'Descrição',
    'service_details_about_author': 'Sobre o autor',
    'service_details_accept': 'Aceitar Serviço',
    'create_service_title': 'Criar Serviço',
    'create_service_form_title': 'Título do serviço',
    'create_service_form_description': 'Descrição',
    'create_service_form_category': 'Categoria',
    'create_service_form_deadline': 'Prazo (ex: 3 dias)',
    'create_service_form_price': 'Valor sugerido (ex: R$ 150)',
    'create_service_form_button': 'Publicar Serviço',
    'dashboard_created': 'Meus Serviços Criados',
    'dashboard_accepted': 'Serviços Aceitos',
    'dashboard_delivered': 'Entregues',
    'dashboard_history': 'Histórico',
    'dashboard_send_delivery': 'Enviar Entrega',
    'dashboard_confirm_completion': 'Confirmar Conclusão',
    'settings_title': 'Configurações',
    'settings_language': 'Idioma',
    'settings_theme': 'Tema',
    'settings_theme_light': 'Claro',
    'settings_theme_dark': 'Escuro (em breve)',
    'settings_account': 'Informações da Conta',
    'settings_account_info': 'Atualize suas informações de perfil e senha.',
    'settings_button_save': 'Salvar Alterações',
    'chat_placeholder': 'Digite sua mensagem...',
    'chat_send_file': 'Anexar arquivo',
    'profile_services_by': 'Serviços de',
    'profile_portfolio': 'Portafólio',
    'profile_skills': 'Habilidades',
    'upload_modal_title': 'Enviar Entrega do Projeto',
    'upload_modal_file': 'Anexar arquivo',
    'upload_modal_message': 'Mensagem (opcional)',
    'upload_modal_button': 'Enviar',
    'upload_modal_cancel': 'Cancelar',
    'toast_service_created': 'Serviço publicado com sucesso!',
    'toast_service_accepted': 'Serviço aceito e movido para o painel.',
    'toast_service_delivered': 'Entrega enviada com sucesso!',
    'toast_service_completed': 'Serviço concluído e arquivado.',
    'toast_language_changed': 'Idioma alterado com sucesso.',
  },
  'en': {
    'home': 'Home',
    'dashboard': 'Dashboard',
    'settings': 'Settings',
    'login': 'Login',
    'register': 'Register',
    'search_placeholder': 'Search for services...',
    'profile': 'Profile',
    'logout': 'Logout',
    'hero_title': 'Find the best freelancers for your project',
    'hero_subtitle': 'Thousands of talented professionals ready to help.',
    'service_card_details': 'View Details',
    'footer_about': 'About',
    'footer_terms': 'Terms',
    'footer_support': 'Support',
    'login_title': 'Sign in to your account',
    'login_email': 'Email',
    'login_password': 'Password',
    'login_button': 'Sign In',
    'login_no_account': "Don't have an account?",
    'register_title': 'Create your account',
    'register_name': 'Full name',
    'register_user_type': 'I am a',
    'register_freelancer': 'Freelancer',
    'register_client': 'Client',
    'register_button': 'Sign Up',
    'register_have_account': 'Already have an account?',
    'service_details_by': 'By',
    'service_details_price': 'Price',
    'service_details_deadline': 'Deadline',
    'service_details_description': 'Description',
    'service_details_about_author': 'About the author',
    'service_details_accept': 'Accept Service',
    'create_service_title': 'Create Service',
    'create_service_form_title': 'Service title',
    'create_service_form_description': 'Description',
    'create_service_form_category': 'Category',
    'create_service_form_deadline': 'Deadline (e.g., 3 days)',
    'create_service_form_price': 'Suggested price (e.g., $50)',
    'create_service_form_button': 'Publish Service',
    'dashboard_created': 'My Created Services',
    'dashboard_accepted': 'Accepted Services',
    'dashboard_delivered': 'Delivered',
    'dashboard_history': 'History',
    'dashboard_send_delivery': 'Send Delivery',
    'dashboard_confirm_completion': 'Confirm Completion',
    'settings_title': 'Settings',
    'settings_language': 'Language',
    'settings_theme': 'Theme',
    'settings_theme_light': 'Light',
    'settings_theme_dark': 'Dark (coming soon)',
    'settings_account': 'Account Information',
    'settings_account_info': 'Update your profile information and password.',
    'settings_button_save': 'Save Changes',
    'chat_placeholder': 'Type your message...',
    'chat_send_file': 'Attach file',
    'profile_services_by': 'Services by',
    'profile_portfolio': 'Portfolio',
    'profile_skills': 'Skills',
    'upload_modal_title': 'Deliver Project',
    'upload_modal_file': 'Attach file',
    'upload_modal_message': 'Message (optional)',
    'upload_modal_button': 'Send',
    'upload_modal_cancel': 'Cancel',
    'toast_service_created': 'Service published successfully!',
    'toast_service_accepted': 'Service accepted and moved to the dashboard.',
    'toast_service_delivered': 'Delivery sent successfully!',
    'toast_service_completed': 'Service completed and archived.',
    'toast_language_changed': 'Language changed successfully.',
  },
  'es': {
    'home': 'Inicio',
    'dashboard': 'Panel',
    'settings': 'Configuración',
    'login': 'Iniciar Sesión',
    'register': 'Registrarse',
    'search_placeholder': 'Buscar servicios...',
    'profile': 'Perfil',
    'logout': 'Cerrar Sesión',
    'hero_title': 'Encuentra los mejores freelancers para tu proyecto',
    'hero_subtitle': 'Miles de profesionales talentosos listos para ayudar.',
    'service_card_details': 'Ver Detalles',
    'footer_about': 'Sobre',
    'footer_terms': 'Términos',
    'footer_support': 'Soporte',
    'login_title': 'Inicia sesión en tu cuenta',
    'login_email': 'Correo electrónico',
    'login_password': 'Contraseña',
    'login_button': 'Iniciar Sesión',
    'login_no_account': '¿No tienes una cuenta?',
    'register_title': 'Crea tu cuenta',
    'register_name': 'Nombre completo',
    'register_user_type': 'Yo soy un',
    'register_freelancer': 'Freelancer',
    'register_client': 'Cliente',
    'register_button': 'Registrarse',
    'register_have_account': '¿Ya tienes una cuenta?',
    'service_details_by': 'Por',
    'service_details_price': 'Precio',
    'service_details_deadline': 'Plazo',
    'service_details_description': 'Descripción',
    'service_details_about_author': 'Sobre el autor',
    'service_details_accept': 'Aceptar Servicio',
    'create_service_title': 'Crear Servicio',
    'create_service_form_title': 'Título del servicio',
    'create_service_form_description': 'Descripción',
    'create_service_form_category': 'Categoría',
    'create_service_form_deadline': 'Plazo (ej: 3 días)',
    'create_service_form_price': 'Precio sugerido (ej: €50)',
    'create_service_form_button': 'Publicar Servicio',
    'dashboard_created': 'Mis Servicios Creados',
    'dashboard_accepted': 'Servicios Aceptados',
    'dashboard_delivered': 'Entregados',
    'dashboard_history': 'Historial',
    'dashboard_send_delivery': 'Enviar Entrega',
    'dashboard_confirm_completion': 'Confirmar Finalización',
    'settings_title': 'Configuración',
    'settings_language': 'Idioma',
    'settings_theme': 'Tema',
    'settings_theme_light': 'Claro',
    'settings_theme_dark': 'Oscuro (próximamente)',
    'settings_account': 'Información de la Cuenta',
    'settings_account_info': 'Actualiza tu información de perfil y contraseña.',
    'settings_button_save': 'Guardar Cambios',
    'chat_placeholder': 'Escribe tu mensaje...',
    'chat_send_file': 'Adjuntar archivo',
    'profile_services_by': 'Servicios de',
    'profile_portfolio': 'Portafolio',
    'profile_skills': 'Habilidades',
    'upload_modal_title': 'Entregar Proyecto',
    'upload_modal_file': 'Adjuntar archivo',
    'upload_modal_message': 'Mensaje (opcional)',
    'upload_modal_button': 'Enviar',
    'upload_modal_cancel': 'Cancelar',
    'toast_service_created': '¡Servicio publicado con éxito!',
    'toast_service_accepted': 'Servicio aceptado y movido al panel.',
    'toast_service_delivered': '¡Entrega enviada con éxito!',
    'toast_service_completed': 'Servicio completado y archivado.',
    'toast_language_changed': 'Idioma cambiado con éxito.',
  }
};