// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://czpykecxwrlfczdtunxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cHlrZWN4d3JsZmN6ZHR1bnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTAwMzEsImV4cCI6MjA3ODQ4NjAzMX0.fAu6gMeTcFkF1gasB_ioNbpD9Ul50pILt0RGbXwoVB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);